import OpenAI from 'openai';

const getClient = () => {
  const apiKey = process.env.FIREWORKS_API_KEY;
  if (!apiKey) {
    throw new Error(
      "FIREWORKS_API_KEY environment variable is required. Set it in .env.local"
    );
  }
  return new OpenAI({
    apiKey,
    baseURL: "https://api.fireworks.ai/inference/v1"
  });
};

/**
 * Generate structured design layout and theme using Kimi via Fireworks.
 * @param {Array} rawSlides - The raw text slides generated by Gemini
 * @returns {object} Parsed JSON response containing theme and layout_mapping
 */
export async function generateDesign(rawSlides) {
  const openai = getClient();

  const systemPrompt = `You are an expert Presentation Designer and Art Director.
You will be given the raw text content of a presentation. Your job is to output a JSON object containing:
1. "theme": A complete custom CSS theme object (colors, fonts, decorative settings) that fits the mood of the content.

The output MUST be valid JSON in this exact structure:
{
  "theme": {
    "colors": {
      "slideBg": "hex color",
      "slideBgAlt": "hex color",
      "cardBg": "hex color",
      "heading": "hex color",
      "body": "hex color",
      "muted": "hex color",
      "accent": "hex color",
      "accentLight": "hex color",
      "accentGlow": "rgba string",
      "border": "rgba string",
      "gradient": "css linear-gradient string"
    },
    "fonts": {
      "heading": "font family string",
      "body": "font family string"
    },
    "decorative": {
      "shapeColor": "hex color",
      "shapeOpacity": number between 0 and 1,
      "accentBarColor": "hex color",
      "cornerRadius": "string (e.g. '12px')"
    }
  }
}
`;

  const userPrompt = JSON.stringify(rawSlides, null, 2);

  const response = await openai.chat.completions.create({
    model: "accounts/fireworks/models/kimi-k2p6",
    response_format: { type: "json_object" },
    messages: [
      { role: "system", content: systemPrompt },
      { role: "user", content: userPrompt }
    ],
    temperature: 0.7,
  });

  const content = response.choices[0].message.content;
  return JSON.parse(content);
}

function extractJson(text) {
  const jsonMatch = text.match(/```(?:json)?\s*([\s\S]*?)\s*```/);
  if (jsonMatch) {
    return jsonMatch[1];
  }
  const start = text.indexOf('{');
  const end = text.lastIndexOf('}');
  if (start !== -1 && end !== -1 && end > start) {
    return text.substring(start, end + 1);
  }
  return text;
}

/**
 * Generate structured JSON from Fireworks (Kimi) with a given system prompt and schema.
 */
export async function generateStructured(
  systemPrompt,
  userPrompt,
  responseSchema
) {
  const openai = getClient();
  const fullSystemPrompt = `${systemPrompt}\n\nYou MUST return your response as a raw, valid JSON object matching this exact schema. Do not include markdown formatting or explanations.\n\nSCHEMA:\n${JSON.stringify(responseSchema, null, 2)}`;

  const response = await openai.chat.completions.create({
    model: "accounts/fireworks/models/kimi-k2p6",
    response_format: { type: "json_object" },
    messages: [
      { role: "system", content: fullSystemPrompt },
      { role: "user", content: userPrompt }
    ],
    temperature: 0.7,
  });

  const textContent = response.choices[0].message.content;
  
  try {
    const cleanJson = extractJson(textContent);
    return JSON.parse(cleanJson);
  } catch (err) {
    console.error("Failed to parse Fireworks JSON:", textContent);
    throw new Error("Invalid JSON returned from model");
  }
}

/**
 * Stream structured JSON from Fireworks (Kimi).
 */
export async function* streamStructured(
  systemPrompt,
  userPrompt,
  responseSchema
) {
  const openai = getClient();
  const fullSystemPrompt = `${systemPrompt}\n\nYou MUST return your response as a raw, valid JSON object matching this exact schema. Do not include markdown formatting or explanations.\n\nSCHEMA:\n${JSON.stringify(responseSchema, null, 2)}`;

  const stream = await openai.chat.completions.create({
    model: "accounts/fireworks/models/kimi-k2p6",
    response_format: { type: "json_object" },
    messages: [
      { role: "system", content: fullSystemPrompt },
      { role: "user", content: userPrompt }
    ],
    temperature: 0.7,
    stream: true,
  });

  let accumulated = "";
  for await (const chunk of stream) {
    const delta = chunk.choices[0]?.delta?.content || "";
    if (delta) {
      accumulated += delta;
      yield { chunk: delta, accumulated };
    }
  }
}
