import OpenAI from 'openai';

const getClient = () => {
  const apiKey = process.env.FIREWORKS_API_KEY;
  if (!apiKey) {
    throw new Error(
      "FIREWORKS_API_KEY environment variable is required. Set it in .env.local"
    );
  }
  return new OpenAI({
    apiKey,
    baseURL: "https://api.fireworks.ai/inference/v1"
  });
};

/**
 * Generate structured design layout and theme using Kimi via Fireworks.
 * @param {Array} rawSlides - The raw text slides generated by Gemini
 * @returns {object} Parsed JSON response containing theme and layout_mapping
 */
export async function generateDesign(rawSlides) {
  const openai = getClient();

  const systemPrompt = `You are an expert Presentation Designer and Art Director.
You will be given the raw text content of a presentation. Your job is to output a JSON object containing:
1. "theme": A complete custom CSS theme object (colors, fonts, decorative settings) that fits the mood of the content.

The output MUST be valid JSON in this exact structure:
{
  "theme": {
    "colors": {
      "slideBg": "hex color",
      "slideBgAlt": "hex color",
      "cardBg": "hex color",
      "heading": "hex color",
      "body": "hex color",
      "muted": "hex color",
      "accent": "hex color",
      "accentLight": "hex color",
      "accentGlow": "rgba string",
      "border": "rgba string",
      "gradient": "css linear-gradient string"
    },
    "fonts": {
      "heading": "font family string",
      "body": "font family string"
    },
    "decorative": {
      "shapeColor": "hex color",
      "shapeOpacity": number between 0 and 1,
      "accentBarColor": "hex color",
      "cornerRadius": "string (e.g. '12px')"
    }
  }
}
`;

  const userPrompt = JSON.stringify(rawSlides, null, 2);

  const response = await openai.chat.completions.create({
    model: "accounts/fireworks/models/kimi-k2p6",
    response_format: { type: "json_object" },
    messages: [
      { role: "system", content: systemPrompt },
      { role: "user", content: userPrompt }
    ],
    temperature: 0.7,
  });

  const content = response.choices[0].message.content;
  return JSON.parse(content);
}
